<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <BridgePlatformToolset Condition="'$(BridgePlatformToolset)'==''">v141</BridgePlatformToolset>

    <BridgeSdk14393Exists Condition="Exists('$(MSBuildProgramFiles32)\Windows Kits\10\Include\10.0.14393.0')">true</BridgeSdk14393Exists>
    <BridgeSdk19041Exists Condition="Exists('$(MSBuildProgramFiles32)\Windows Kits\10\Include\10.0.19041.0')">true</BridgeSdk19041Exists>
    <BridgeSdk26100Exists Condition="Exists('$(MSBuildProgramFiles32)\Windows Kits\10\Include\10.0.26100.0')">true</BridgeSdk26100Exists>

    <BridgeWindowsTargetPlatformVersion Condition="'$(BridgeWindowsTargetPlatformVersion)'=='' and '$(BridgeSdk14393Exists)'=='true'">10.0.14393.0</BridgeWindowsTargetPlatformVersion>
    <BridgeWindowsTargetPlatformVersion Condition="'$(BridgeWindowsTargetPlatformVersion)'=='' and '$(BridgeSdk19041Exists)'=='true'">10.0.19041.0</BridgeWindowsTargetPlatformVersion>
    <BridgeWindowsTargetPlatformVersion Condition="'$(BridgeWindowsTargetPlatformVersion)'=='' and '$(BridgeSdk26100Exists)'=='true'">10.0.26100.0</BridgeWindowsTargetPlatformVersion>
    <BridgeWindowsTargetPlatformVersion Condition="'$(BridgeWindowsTargetPlatformVersion)'==''">10.0</BridgeWindowsTargetPlatformVersion>

    <BridgeWindowsTargetPlatformMinVersion Condition="'$(BridgeWindowsTargetPlatformMinVersion)'==''">10.0.14393.0</BridgeWindowsTargetPlatformMinVersion>
  </PropertyGroup>
</Project>
